definition:
  - datasets: productivity
imports:
  - language: cypher
    files:
      - cypher/calendar-years.cypher
      - ../geo-specific-codelist/nuts-geography.cypher
      - cypher/productivity.cypher
      - cypher/smoothing.cypher
  - language: gremlin
    files:
      - gremlin/calendar-years.grm
      - ../geo-specific-codelist/gremlin/nuts-geography.grm
      - gremlin/productivity.grm
      - gremlin/smoothing.grm
