CREATE CONSTRAINT ON (n:`_code_census-1961-number-of-rooms`) ASSERT n.code IS UNIQUE;
CREATE CONSTRAINT ON (n:`_code_list_census-1961-number-of-rooms`) ASSERT n.code IS UNIQUE;
CREATE (node:`_code_list`:`_code_list_census-1961-number-of-rooms` { label:"numberofrooms", edition:"one-off" });
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"1-room" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"1-room" }) MERGE (node)-[:usedBy { label:"1 room"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"more-than-10-rooms" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"more-than-10-rooms" }) MERGE (node)-[:usedBy { label:"More than 10 rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"2-rooms" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"2-rooms" }) MERGE (node)-[:usedBy { label:"2 rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"3-rooms" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"3-rooms" }) MERGE (node)-[:usedBy { label:"3 rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"4-rooms" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"4-rooms" }) MERGE (node)-[:usedBy { label:"4 rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"5-rooms" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"5-rooms" }) MERGE (node)-[:usedBy { label:"5 rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"6-rooms" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"6-rooms" }) MERGE (node)-[:usedBy { label:"6 rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"7-rooms" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"7-rooms" }) MERGE (node)-[:usedBy { label:"7 rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"8-9-rooms" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"8-9-rooms" }) MERGE (node)-[:usedBy { label:"8 9 rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"average-number-of-persons-per-room" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"average-number-of-persons-per-room" }) MERGE (node)-[:usedBy { label:"Average number of persons per room"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"total-households" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"total-households" }) MERGE (node)-[:usedBy { label:"Total households"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"total-persons-in-households" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"total-persons-in-households" }) MERGE (node)-[:usedBy { label:"Total persons in households"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"total-rooms-occupied" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"total-rooms-occupied" }) MERGE (node)-[:usedBy { label:"Total rooms occupied"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"occupied-rooms" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"occupied-rooms" }) MERGE (node)-[:usedBy { label:"Occupied rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"partly-vacant-dwellings" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"partly-vacant-dwellings" }) MERGE (node)-[:usedBy { label:"Partly vacant dwellings"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"total-dwellings" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"total-dwellings" }) MERGE (node)-[:usedBy { label:"Total dwellings"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"total-rooms" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"total-rooms" }) MERGE (node)-[:usedBy { label:"Total rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"vacant-dwellings" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"vacant-dwellings" }) MERGE (node)-[:usedBy { label:"Vacant dwellings"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"vacant-rooms" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"vacant-rooms" }) MERGE (node)-[:usedBy { label:"Vacant rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-number-of-rooms` { value:"fewer-than-10-rooms" });
MATCH (parent:`_code_list`:`_code_list_census-1961-number-of-rooms`),(node:`_code`:`_code_census-1961-number-of-rooms` { value:"fewer-than-10-rooms" }) MERGE (node)-[:usedBy { label:"Fewer than 10 rooms"}]->(parent);
