CREATE (node:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type` { label:'establishmenttype', edition:'one-off' });
CREATE CONSTRAINT ON (n:`_code_list_census-1961-non-private-population-establishment-type`) ASSERT n.value IS UNIQUE;
CREATE CONSTRAINT ON (n:`_code_census-1961-non-private-population-establishment-type`) ASSERT n.value IS UNIQUE;

MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'childrens-homes' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'childrens-homes' }) MERGE (node)-[:usedBy { label:"Children's homes"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'civilian-vessels' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'civilian-vessels' }) MERGE (node)-[:usedBy { label:"Civilian vessels"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'defence-establishments' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'defence-establishments' }) MERGE (node)-[:usedBy { label:"Defence establishments"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'educational-establishments' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'educational-establishments' }) MERGE (node)-[:usedBy { label:"Educational establishments"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'homes-for-the-aged' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'homes-for-the-aged' }) MERGE (node)-[:usedBy { label:"Homes for the aged"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'homes-for-the-aged-and-disabled' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'homes-for-the-aged-and-disabled' }) MERGE (node)-[:usedBy { label:"Homes for the aged and disabled"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'homes-for-the-disabled' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'homes-for-the-disabled' }) MERGE (node)-[:usedBy { label:"Homes for the disabled"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'miscellaneous' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'miscellaneous' }) MERGE (node)-[:usedBy { label:"Miscellaneous"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'miscellaneous-communal-establishments' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'miscellaneous-communal-establishments' }) MERGE (node)-[:usedBy { label:"Miscellaneous communal establishments"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'nhs-acute-hospital' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'nhs-acute-hospital' }) MERGE (node)-[:usedBy { label:"NHS acute hospital"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'nhs-chronic-hospital' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'nhs-chronic-hospital' }) MERGE (node)-[:usedBy { label:"NHS chronic hospital"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'nhs-isolation-hospital' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'nhs-isolation-hospital' }) MERGE (node)-[:usedBy { label:"NHS isolation hospital"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'nhs-other-hospital' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'nhs-other-hospital' }) MERGE (node)-[:usedBy { label:"NHS other hospital"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'nhs-psychiatric-hospital' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'nhs-psychiatric-hospital' }) MERGE (node)-[:usedBy { label:"NHS psychiatric hospital"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'non-nhs-convalescent-hospital' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'non-nhs-convalescent-hospital' }) MERGE (node)-[:usedBy { label:"Non-NHS convalescent hospital"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'non-nhs-maternity-hospital' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'non-nhs-maternity-hospital' }) MERGE (node)-[:usedBy { label:"Non-NHS maternity hospital"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'non-nhs-other-hospital' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'non-nhs-other-hospital' }) MERGE (node)-[:usedBy { label:"Non-NHS other hospital"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'non-nhs-psychiatric-hospital' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'non-nhs-psychiatric-hospital' }) MERGE (node)-[:usedBy { label:"Non-NHS psychiatric hospital"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'places-of-detention' });
MATCH (parent:`_code_list`:`_code_list_census-1961-non-private-population-establishment-type`),(node:`_code`:`_code_census-1961-non-private-population-establishment-type` { value:'places-of-detention' }) MERGE (node)-[:usedBy { label:"Places of detention"}]->(parent);

