CREATE (node:`_code_list`:`_code_list_census-1961-hotel-variable` { label:'hotelvariable', edition:'one-off' });
CREATE CONSTRAINT ON (n:`_code_list_census-1961-hotel-variable`) ASSERT n.value IS UNIQUE;
CREATE CONSTRAINT ON (n:`_code_census-1961-hotel-variable`) ASSERT n.value IS UNIQUE;

MERGE (node:`_code`:`_code_census-1961-hotel-variable` { value:'all-enumerated-in-hotels-with-fewer-than-10-rooms' });
MATCH (parent:`_code_list`:`_code_list_census-1961-hotel-variable`),(node:`_code`:`_code_census-1961-hotel-variable` { value:'all-enumerated-in-hotels-with-fewer-than-10-rooms' }) MERGE (node)-[:usedBy { label:"All enumerated in hotels with fewer than 10 rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-hotel-variable` { value:'hotels-with-10-14-rooms' });
MATCH (parent:`_code_list`:`_code_list_census-1961-hotel-variable`),(node:`_code`:`_code_census-1961-hotel-variable` { value:'hotels-with-10-14-rooms' }) MERGE (node)-[:usedBy { label:"Hotels with 10-14 rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-hotel-variable` { value:'hotels-with-100-199-rooms' });
MATCH (parent:`_code_list`:`_code_list_census-1961-hotel-variable`),(node:`_code`:`_code_census-1961-hotel-variable` { value:'hotels-with-100-199-rooms' }) MERGE (node)-[:usedBy { label:"Hotels with 100-199 rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-hotel-variable` { value:'hotels-with-15-24-rooms' });
MATCH (parent:`_code_list`:`_code_list_census-1961-hotel-variable`),(node:`_code`:`_code_census-1961-hotel-variable` { value:'hotels-with-15-24-rooms' }) MERGE (node)-[:usedBy { label:"Hotels with 15-24 rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-hotel-variable` { value:'hotels-with-200+-rooms' });
MATCH (parent:`_code_list`:`_code_list_census-1961-hotel-variable`),(node:`_code`:`_code_census-1961-hotel-variable` { value:'hotels-with-200+-rooms' }) MERGE (node)-[:usedBy { label:"Hotels with 200+ rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-hotel-variable` { value:'hotels-with-25-49-rooms' });
MATCH (parent:`_code_list`:`_code_list_census-1961-hotel-variable`),(node:`_code`:`_code_census-1961-hotel-variable` { value:'hotels-with-25-49-rooms' }) MERGE (node)-[:usedBy { label:"Hotels with 25-49 rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-hotel-variable` { value:'hotels-with-50-99-rooms' });
MATCH (parent:`_code_list`:`_code_list_census-1961-hotel-variable`),(node:`_code`:`_code_census-1961-hotel-variable` { value:'hotels-with-50-99-rooms' }) MERGE (node)-[:usedBy { label:"Hotels with 50-99 rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-hotel-variable` { value:'manager-and-staff' });
MATCH (parent:`_code_list`:`_code_list_census-1961-hotel-variable`),(node:`_code`:`_code_census-1961-hotel-variable` { value:'manager-and-staff' }) MERGE (node)-[:usedBy { label:"Manager and staff"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-hotel-variable` { value:'number-of-hotels-with-fewer-than-10-rooms' });
MATCH (parent:`_code_list`:`_code_list_census-1961-hotel-variable`),(node:`_code`:`_code_census-1961-hotel-variable` { value:'number-of-hotels-with-fewer-than-10-rooms' }) MERGE (node)-[:usedBy { label:"Number of hotels with fewer than 10 rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-hotel-variable` { value:'persons-enumerated-in-hotels-with-fewer-than-10-rooms' });
MATCH (parent:`_code_list`:`_code_list_census-1961-hotel-variable`),(node:`_code`:`_code_census-1961-hotel-variable` { value:'persons-enumerated-in-hotels-with-fewer-than-10-rooms' }) MERGE (node)-[:usedBy { label:"Persons enumerated in hotels with fewer than 10 rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-hotel-variable` { value:'relatives-of-staff' });
MATCH (parent:`_code_list`:`_code_list_census-1961-hotel-variable`),(node:`_code`:`_code_census-1961-hotel-variable` { value:'relatives-of-staff' }) MERGE (node)-[:usedBy { label:"Relatives of staff"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-hotel-variable` { value:'resident-guests' });
MATCH (parent:`_code_list`:`_code_list_census-1961-hotel-variable`),(node:`_code`:`_code_census-1961-hotel-variable` { value:'resident-guests' }) MERGE (node)-[:usedBy { label:"Resident guests"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-hotel-variable` { value:'resident-visitors' });
MATCH (parent:`_code_list`:`_code_list_census-1961-hotel-variable`),(node:`_code`:`_code_census-1961-hotel-variable` { value:'resident-visitors' }) MERGE (node)-[:usedBy { label:"Resident visitors"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-hotel-variable` { value:'total-rooms-in-hotels-with-10-or-more-rooms' });
MATCH (parent:`_code_list`:`_code_list_census-1961-hotel-variable`),(node:`_code`:`_code_census-1961-hotel-variable` { value:'total-rooms-in-hotels-with-10-or-more-rooms' }) MERGE (node)-[:usedBy { label:"Total rooms in hotels with 10 or more rooms"}]->(parent);
MERGE (node:`_code`:`_code_census-1961-hotel-variable` { value:'total-rooms-in-hotels-with-fewer-than-10-rooms' });
MATCH (parent:`_code_list`:`_code_list_census-1961-hotel-variable`),(node:`_code`:`_code_census-1961-hotel-variable` { value:'total-rooms-in-hotels-with-fewer-than-10-rooms' }) MERGE (node)-[:usedBy { label:"Total rooms in hotels with fewer than 10 rooms"}]->(parent);

