CREATE CONSTRAINT ON (n:`_code_welsh-household-composition`) ASSERT n.code IS UNIQUE;
CREATE CONSTRAINT ON (n:`_code_list_welsh-household-composition`) ASSERT n.code IS UNIQUE;
CREATE (node:`_code_list`:`_code_list_welsh-household-composition` { label:"welshhouseholdcomposition", edition:"one-off" });
MERGE (node:`_code`:`_code_welsh-household-composition` { value:"all-categories-welsh-household-composition" });
MATCH (parent:`_code_list`:`_code_list_welsh-household-composition`),(node:`_code`:`_code_welsh-household-composition` { value:"all-categories-welsh-household-composition" }) MERGE (node)-[:usedBy { label:"All categories: Welsh household composition"}]->(parent);
MERGE (node:`_code`:`_code_welsh-household-composition` { value:"couple-household-total" });
MATCH (parent:`_code_list`:`_code_list_welsh-household-composition`),(node:`_code`:`_code_welsh-household-composition` { value:"couple-household-total" }) MERGE (node)-[:usedBy { label:"Couple household: Total"}]->(parent);
MERGE (node:`_code`:`_code_welsh-household-composition` { value:"couple-household-no-adults-can-speak-welsh" });
MATCH (parent:`_code_list`:`_code_list_welsh-household-composition`),(node:`_code`:`_code_welsh-household-composition` { value:"couple-household-no-adults-can-speak-welsh" }) MERGE (node)-[:usedBy { label:"Couple household: No adults can speak Welsh"}]->(parent);
MERGE (node:`_code`:`_code_welsh-household-composition` { value:"couple-household-one-adult-can-speak-welsh" });
MATCH (parent:`_code_list`:`_code_list_welsh-household-composition`),(node:`_code`:`_code_welsh-household-composition` { value:"couple-household-one-adult-can-speak-welsh" }) MERGE (node)-[:usedBy { label:"Couple household: One adult can speak Welsh"}]->(parent);
MERGE (node:`_code`:`_code_welsh-household-composition` { value:"couple-household-two-or-more-adults-can-speak-welsh" });
MATCH (parent:`_code_list`:`_code_list_welsh-household-composition`),(node:`_code`:`_code_welsh-household-composition` { value:"couple-household-two-or-more-adults-can-speak-welsh" }) MERGE (node)-[:usedBy { label:"Couple household: Two or more adults can speak Welsh"}]->(parent);
MERGE (node:`_code`:`_code_welsh-household-composition` { value:"lone-parent-household-total" });
MATCH (parent:`_code_list`:`_code_list_welsh-household-composition`),(node:`_code`:`_code_welsh-household-composition` { value:"lone-parent-household-total" }) MERGE (node)-[:usedBy { label:"Lone parent household: Total"}]->(parent);
MERGE (node:`_code`:`_code_welsh-household-composition` { value:"lone-parent-household-no-adults-can-speak-welsh" });
MATCH (parent:`_code_list`:`_code_list_welsh-household-composition`),(node:`_code`:`_code_welsh-household-composition` { value:"lone-parent-household-no-adults-can-speak-welsh" }) MERGE (node)-[:usedBy { label:"Lone parent household: No adults can speak Welsh"}]->(parent);
MERGE (node:`_code`:`_code_welsh-household-composition` { value:"lone-parent-household-one-adult-can-speak-welsh" });
MATCH (parent:`_code_list`:`_code_list_welsh-household-composition`),(node:`_code`:`_code_welsh-household-composition` { value:"lone-parent-household-one-adult-can-speak-welsh" }) MERGE (node)-[:usedBy { label:"Lone parent household: One adult can speak Welsh"}]->(parent);
MERGE (node:`_code`:`_code_welsh-household-composition` { value:"lone-parent-household-two-or-more-adults-can-speak-welsh" });
MATCH (parent:`_code_list`:`_code_list_welsh-household-composition`),(node:`_code`:`_code_welsh-household-composition` { value:"lone-parent-household-two-or-more-adults-can-speak-welsh" }) MERGE (node)-[:usedBy { label:"Lone parent household: Two or more adults can speak Welsh"}]->(parent);
