CREATE CONSTRAINT ON (n:`_code_construction-classifications`) ASSERT n.code IS UNIQUE;
CREATE CONSTRAINT ON (n:`_code_list_construction-classifications`) ASSERT n.code IS UNIQUE;
CREATE (node:`_code_list`:`_code_list_construction-classifications` { label:"typeofwork", edition:"one-off" });
MERGE (node:`_code`:`_code_construction-classifications` { value:"1" });
MATCH (parent:`_code_list`:`_code_list_construction-classifications`),(node:`_code`:`_code_construction-classifications` { value:"1" }) MERGE (node)-[:usedBy { label:"Total All Work"}]->(parent);
MERGE (node:`_code`:`_code_construction-classifications` { value:"1-1" });
MATCH (parent:`_code_list`:`_code_list_construction-classifications`),(node:`_code`:`_code_construction-classifications` { value:"1-1" }) MERGE (node)-[:usedBy { label:"Repair & Maintenance"}]->(parent);
MERGE (node:`_code`:`_code_construction-classifications` { value:"1-1-1" });
MATCH (parent:`_code_list`:`_code_list_construction-classifications`),(node:`_code`:`_code_construction-classifications` { value:"1-1-1" }) MERGE (node)-[:usedBy { label:"Housing R & M"}]->(parent);
MERGE (node:`_code`:`_code_construction-classifications` { value:"1-1-1-1" });
MATCH (parent:`_code_list`:`_code_list_construction-classifications`),(node:`_code`:`_code_construction-classifications` { value:"1-1-1-1" }) MERGE (node)-[:usedBy { label:"Public housing R & M"}]->(parent);
MERGE (node:`_code`:`_code_construction-classifications` { value:"1-1-1-2" });
MATCH (parent:`_code_list`:`_code_list_construction-classifications`),(node:`_code`:`_code_construction-classifications` { value:"1-1-1-2" }) MERGE (node)-[:usedBy { label:"Private housing R & M"}]->(parent);
MERGE (node:`_code`:`_code_construction-classifications` { value:"1-1-2" });
MATCH (parent:`_code_list`:`_code_list_construction-classifications`),(node:`_code`:`_code_construction-classifications` { value:"1-1-2" }) MERGE (node)-[:usedBy { label:"Non-housing R & M"}]->(parent);
MERGE (node:`_code`:`_code_construction-classifications` { value:"1-1-2-1-1" });
MATCH (parent:`_code_list`:`_code_list_construction-classifications`),(node:`_code`:`_code_construction-classifications` { value:"1-1-2-1-1" }) MERGE (node)-[:usedBy { label:"Public other work R & M"}]->(parent);
MERGE (node:`_code`:`_code_construction-classifications` { value:"1-1-2-1-2" });
MATCH (parent:`_code_list`:`_code_list_construction-classifications`),(node:`_code`:`_code_construction-classifications` { value:"1-1-2-1-2" }) MERGE (node)-[:usedBy { label:"Private other work R & M"}]->(parent);
MERGE (node:`_code`:`_code_construction-classifications` { value:"1-1-2-2" });
MATCH (parent:`_code_list`:`_code_list_construction-classifications`),(node:`_code`:`_code_construction-classifications` { value:"1-1-2-2" }) MERGE (node)-[:usedBy { label:"Infrastructure R & M"}]->(parent);
MERGE (node:`_code`:`_code_construction-classifications` { value:"1-2" });
MATCH (parent:`_code_list`:`_code_list_construction-classifications`),(node:`_code`:`_code_construction-classifications` { value:"1-2" }) MERGE (node)-[:usedBy { label:"All New Work"}]->(parent);
MERGE (node:`_code`:`_code_construction-classifications` { value:"1-2-1" });
MATCH (parent:`_code_list`:`_code_list_construction-classifications`),(node:`_code`:`_code_construction-classifications` { value:"1-2-1" }) MERGE (node)-[:usedBy { label:"New Housing"}]->(parent);
MERGE (node:`_code`:`_code_construction-classifications` { value:"1-2-1-1" });
MATCH (parent:`_code_list`:`_code_list_construction-classifications`),(node:`_code`:`_code_construction-classifications` { value:"1-2-1-1" }) MERGE (node)-[:usedBy { label:"Public new housing"}]->(parent);
MERGE (node:`_code`:`_code_construction-classifications` { value:"1-2-1-2" });
MATCH (parent:`_code_list`:`_code_list_construction-classifications`),(node:`_code`:`_code_construction-classifications` { value:"1-2-1-2" }) MERGE (node)-[:usedBy { label:"Private new housing"}]->(parent);
MERGE (node:`_code`:`_code_construction-classifications` { value:"1-2-2-1-1" });
MATCH (parent:`_code_list`:`_code_list_construction-classifications`),(node:`_code`:`_code_construction-classifications` { value:"1-2-2-1-1" }) MERGE (node)-[:usedBy { label:"Public ONW"}]->(parent);
MERGE (node:`_code`:`_code_construction-classifications` { value:"1-2-2-1-2-1" });
MATCH (parent:`_code_list`:`_code_list_construction-classifications`),(node:`_code`:`_code_construction-classifications` { value:"1-2-2-1-2-1" }) MERGE (node)-[:usedBy { label:"Private Industrial ONW"}]->(parent);
MERGE (node:`_code`:`_code_construction-classifications` { value:"1-2-2-1-2-2" });
MATCH (parent:`_code_list`:`_code_list_construction-classifications`),(node:`_code`:`_code_construction-classifications` { value:"1-2-2-1-2-2" }) MERGE (node)-[:usedBy { label:"Private Commercial ONW"}]->(parent);
MERGE (node:`_code`:`_code_construction-classifications` { value:"1-2-3" });
MATCH (parent:`_code_list`:`_code_list_construction-classifications`),(node:`_code`:`_code_construction-classifications` { value:"1-2-3" }) MERGE (node)-[:usedBy { label:"Infrastructure"}]->(parent);
