CREATE CONSTRAINT ON (n:`_code_faster-indicators-sic-recordtype`) ASSERT n.code IS UNIQUE;
CREATE CONSTRAINT ON (n:`_code_list_faster-indicators-sic-recordtype`) ASSERT n.code IS UNIQUE;
CREATE (node:`_code_list`:`_code_list_faster-indicators-sic-recordtype` { label:"sicrecordtype", edition:"one-off" });
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"total-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"total-tax-due" })                 MERGE (node)-[:usedBy { label:"Total - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"total-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"total-repayment-claim" })                 MERGE (node)-[:usedBy { label:"Total - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"total-re-input-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"total-re-input-tax-due" })                 MERGE (node)-[:usedBy { label:"Total - Re-input tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"total-re-input-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"total-re-input-repayment-claim" })                 MERGE (node)-[:usedBy { label:"Total - Re-input repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"total-replacements-tax-due-and-repayments" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"total-replacements-tax-due-and-repayments" })                 MERGE (node)-[:usedBy { label:"Total - Replacements (Tax due and repayments)"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"agriculture-forestry-and-fishing-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"agriculture-forestry-and-fishing-tax-due" })                 MERGE (node)-[:usedBy { label:"Agriculture, forestry and fishing - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"agriculture-forestry-and-fishing-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"agriculture-forestry-and-fishing-repayment-claim" })                 MERGE (node)-[:usedBy { label:"Agriculture, forestry and fishing - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"agriculture-forestry-and-fishing-re-input-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"agriculture-forestry-and-fishing-re-input-tax-due" })                 MERGE (node)-[:usedBy { label:"Agriculture, forestry and fishing - Re-input tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"agriculture-forestry-and-fishing-re-input-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"agriculture-forestry-and-fishing-re-input-repayment-claim" })                 MERGE (node)-[:usedBy { label:"Agriculture, forestry and fishing - Re-input repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"production-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"production-tax-due" })                 MERGE (node)-[:usedBy { label:"Production - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"production-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"production-repayment-claim" })                 MERGE (node)-[:usedBy { label:"Production - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"production-re-input-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"production-re-input-tax-due" })                 MERGE (node)-[:usedBy { label:"Production - Re-input tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"production-re-input-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"production-re-input-repayment-claim" })                 MERGE (node)-[:usedBy { label:"Production - Re-input repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"construction-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"construction-tax-due" })                 MERGE (node)-[:usedBy { label:"Construction - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"construction-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"construction-repayment-claim" })                 MERGE (node)-[:usedBy { label:"Construction - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"construction-re-input-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"construction-re-input-tax-due" })                 MERGE (node)-[:usedBy { label:"Construction - Re-input tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"construction-re-input-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"construction-re-input-repayment-claim" })                 MERGE (node)-[:usedBy { label:"Construction - Re-input repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"services-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"services-tax-due" })                 MERGE (node)-[:usedBy { label:"Services - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"services-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"services-repayment-claim" })                 MERGE (node)-[:usedBy { label:"Services - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"services-re-input-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"services-re-input-tax-due" })                 MERGE (node)-[:usedBy { label:"Services - Re-input tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"services-re-input-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"services-re-input-repayment-claim" })                 MERGE (node)-[:usedBy { label:"Services - Re-input repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"a-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"a-tax-due" })                 MERGE (node)-[:usedBy { label:"A - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"a-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"a-repayment-claim" })                 MERGE (node)-[:usedBy { label:"A - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"a-re-input-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"a-re-input-tax-due" })                 MERGE (node)-[:usedBy { label:"A - Re-input tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"a-re-input-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"a-re-input-repayment-claim" })                 MERGE (node)-[:usedBy { label:"A - Re-input repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"b-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"b-tax-due" })                 MERGE (node)-[:usedBy { label:"B - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"b-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"b-repayment-claim" })                 MERGE (node)-[:usedBy { label:"B - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"c-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"c-tax-due" })                 MERGE (node)-[:usedBy { label:"C - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"c-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"c-repayment-claim" })                 MERGE (node)-[:usedBy { label:"C - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"d-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"d-tax-due" })                 MERGE (node)-[:usedBy { label:"D - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"d-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"d-repayment-claim" })                 MERGE (node)-[:usedBy { label:"D - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"e-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"e-tax-due" })                 MERGE (node)-[:usedBy { label:"E - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"e-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"e-repayment-claim" })                 MERGE (node)-[:usedBy { label:"E - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"f-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"f-tax-due" })                 MERGE (node)-[:usedBy { label:"F - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"f-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"f-repayment-claim" })                 MERGE (node)-[:usedBy { label:"F - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"f-re-input-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"f-re-input-tax-due" })                 MERGE (node)-[:usedBy { label:"F - Re-input tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"f-re-input-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"f-re-input-repayment-claim" })                 MERGE (node)-[:usedBy { label:"F - Re-input repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"g-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"g-tax-due" })                 MERGE (node)-[:usedBy { label:"G - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"g-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"g-repayment-claim" })                 MERGE (node)-[:usedBy { label:"G - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"g-re-input-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"g-re-input-tax-due" })                 MERGE (node)-[:usedBy { label:"G - Re-input tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"g-re-input-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"g-re-input-repayment-claim" })                 MERGE (node)-[:usedBy { label:"G - Re-input repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"h-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"h-tax-due" })                 MERGE (node)-[:usedBy { label:"H - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"h-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"h-repayment-claim" })                 MERGE (node)-[:usedBy { label:"H - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"h-re-input-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"h-re-input-tax-due" })                 MERGE (node)-[:usedBy { label:"H - Re-input tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"h-re-input-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"h-re-input-repayment-claim" })                 MERGE (node)-[:usedBy { label:"H - Re-input repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"i-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"i-tax-due" })                 MERGE (node)-[:usedBy { label:"I - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"i-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"i-repayment-claim" })                 MERGE (node)-[:usedBy { label:"I - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"i-re-input-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"i-re-input-tax-due" })                 MERGE (node)-[:usedBy { label:"I - Re-input tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"i-re-input-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"i-re-input-repayment-claim" })                 MERGE (node)-[:usedBy { label:"I - Re-input repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"j-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"j-tax-due" })                 MERGE (node)-[:usedBy { label:"J - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"j-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"j-repayment-claim" })                 MERGE (node)-[:usedBy { label:"J - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"j-re-input-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"j-re-input-tax-due" })                 MERGE (node)-[:usedBy { label:"J - Re-input tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"j-re-input-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"j-re-input-repayment-claim" })                 MERGE (node)-[:usedBy { label:"J - Re-input repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"k-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"k-tax-due" })                 MERGE (node)-[:usedBy { label:"K - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"k-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"k-repayment-claim" })                 MERGE (node)-[:usedBy { label:"K - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"l-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"l-tax-due" })                 MERGE (node)-[:usedBy { label:"L - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"l-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"l-repayment-claim" })                 MERGE (node)-[:usedBy { label:"L - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"l-re-input-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"l-re-input-tax-due" })                 MERGE (node)-[:usedBy { label:"L - Re-input tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"l-re-input-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"l-re-input-repayment-claim" })                 MERGE (node)-[:usedBy { label:"L - Re-input repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"m-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"m-tax-due" })                 MERGE (node)-[:usedBy { label:"M - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"m-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"m-repayment-claim" })                 MERGE (node)-[:usedBy { label:"M - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"m-re-input-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"m-re-input-tax-due" })                 MERGE (node)-[:usedBy { label:"M - Re-input tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"m-re-input-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"m-re-input-repayment-claim" })                 MERGE (node)-[:usedBy { label:"M - Re-input repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"n-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"n-tax-due" })                 MERGE (node)-[:usedBy { label:"N - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"n-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"n-repayment-claim" })                 MERGE (node)-[:usedBy { label:"N - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"n-re-input-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"n-re-input-tax-due" })                 MERGE (node)-[:usedBy { label:"N - Re-input tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"n-re-input-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"n-re-input-repayment-claim" })                 MERGE (node)-[:usedBy { label:"N - Re-input repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"p-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"p-tax-due" })                 MERGE (node)-[:usedBy { label:"P - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"p-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"p-repayment-claim" })                 MERGE (node)-[:usedBy { label:"P - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"q-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"q-tax-due" })                 MERGE (node)-[:usedBy { label:"Q - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"q-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"q-repayment-claim" })                 MERGE (node)-[:usedBy { label:"Q - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"r-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"r-tax-due" })                 MERGE (node)-[:usedBy { label:"R - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"r-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"r-repayment-claim" })                 MERGE (node)-[:usedBy { label:"R - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"r-re-input-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"r-re-input-repayment-claim" })                 MERGE (node)-[:usedBy { label:"R - Re-input repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"s-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"s-tax-due" })                 MERGE (node)-[:usedBy { label:"S - Tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"s-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"s-repayment-claim" })                 MERGE (node)-[:usedBy { label:"S - Repayment claim"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"s-re-input-tax-due" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"s-re-input-tax-due" })                 MERGE (node)-[:usedBy { label:"S - Re-input tax due"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"s-re-input-repayment-claim" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-recordtype`),                (node:`_code`:`_code_faster-indicators-sic-recordtype` { value:"s-re-input-repayment-claim" })                 MERGE (node)-[:usedBy { label:"S - Re-input repayment claim"}]->(parent);
