CREATE CONSTRAINT ON (n:`_code_faster-indicators-sic-estimate`) ASSERT n.code IS UNIQUE;
CREATE CONSTRAINT ON (n:`_code_list_faster-indicators-sic-estimate`) ASSERT n.code IS UNIQUE;
CREATE (node:`_code_list`:`_code_list_faster-indicators-sic-estimate` { label:"sicestimate", edition:"one-off" });
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"total-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"total-M2" })                 MERGE (node)-[:usedBy { label:"Total - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"agriculture-forestry-and-fishing-M1" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"agriculture-forestry-and-fishing-M1" })                 MERGE (node)-[:usedBy { label:"Agriculture, forestry and fishing - M1"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"agriculture-forestry-and-fishing-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"agriculture-forestry-and-fishing-M2" })                 MERGE (node)-[:usedBy { label:"Agriculture, forestry and fishing - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"production-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"production-M2" })                 MERGE (node)-[:usedBy { label:"Production - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"construction-M1" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"construction-M1" })                 MERGE (node)-[:usedBy { label:"Construction - M1"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"construction-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"construction-M2" })                 MERGE (node)-[:usedBy { label:"Construction - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"services-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"services-M2" })                 MERGE (node)-[:usedBy { label:"Services - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"a-M1" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"a-M1" })                 MERGE (node)-[:usedBy { label:"A - M1"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"a-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"a-M2" })                 MERGE (node)-[:usedBy { label:"A - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"b-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"b-M2" })                 MERGE (node)-[:usedBy { label:"B - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"c-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"c-M2" })                 MERGE (node)-[:usedBy { label:"C - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"d-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"d-M2" })                 MERGE (node)-[:usedBy { label:"D - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"e-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"e-M2" })                 MERGE (node)-[:usedBy { label:"E - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"f-M1" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"f-M1" })                 MERGE (node)-[:usedBy { label:"F - M1"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"f-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"f-M2" })                 MERGE (node)-[:usedBy { label:"F - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"g-M1" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"g-M1" })                 MERGE (node)-[:usedBy { label:"G - M1"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"g-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"g-M2" })                 MERGE (node)-[:usedBy { label:"G - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"h-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"h-M2" })                 MERGE (node)-[:usedBy { label:"H - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"i-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"i-M2" })                 MERGE (node)-[:usedBy { label:"I - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"j-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"j-M2" })                 MERGE (node)-[:usedBy { label:"J - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"l-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"l-M2" })                 MERGE (node)-[:usedBy { label:"L - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"m-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"m-M2" })                 MERGE (node)-[:usedBy { label:"M - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"n-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"n-M2" })                 MERGE (node)-[:usedBy { label:"N - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"o-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"o-M2" })                 MERGE (node)-[:usedBy { label:"O - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"p-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"p-M2" })                 MERGE (node)-[:usedBy { label:"P - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"q-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"q-M2" })                 MERGE (node)-[:usedBy { label:"Q - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"r-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"r-M2" })                 MERGE (node)-[:usedBy { label:"R - M2"}]->(parent);
MERGE (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"s-M2" });
MATCH (parent:`_code_list`:`_code_list_faster-indicators-sic-estimate`),                (node:`_code`:`_code_faster-indicators-sic-estimate` { value:"s-M2" })                 MERGE (node)-[:usedBy { label:"S - M2"}]->(parent);
