CREATE CONSTRAINT ON (n:`_code_healthcare-financing-scheme`) ASSERT n.code IS UNIQUE;
CREATE CONSTRAINT ON (n:`_code_list_healthcare-financing-scheme`) ASSERT n.code IS UNIQUE;
CREATE (node:`_code_list`:`_code_list_healthcare-financing-scheme` { label:"Financing Scheme", edition:"one-off" });
MERGE (node:`_code`:`_code_healthcare-financing-scheme` { value:"HFTOT" });
MATCH (parent:`_code_list`:`_code_list_healthcare-financing-scheme`),(node:`_code`:`_code_healthcare-financing-scheme` { value:"HFTOT" }) MERGE (node)-[:usedBy { label:"All financing schemes"}]->(parent);
MERGE (node:`_code`:`_code_healthcare-financing-scheme` { value:"HF11" });
MATCH (parent:`_code_list`:`_code_list_healthcare-financing-scheme`),(node:`_code`:`_code_healthcare-financing-scheme` { value:"HF11" }) MERGE (node)-[:usedBy { label:"Government schemes"}]->(parent);
MERGE (node:`_code`:`_code_healthcare-financing-scheme` { value:"HF21" });
MATCH (parent:`_code_list`:`_code_list_healthcare-financing-scheme`),(node:`_code`:`_code_healthcare-financing-scheme` { value:"HF21" }) MERGE (node)-[:usedBy { label:"Voluntary health insurance schemes"}]->(parent);
MERGE (node:`_code`:`_code_healthcare-financing-scheme` { value:"HF22" });
MATCH (parent:`_code_list`:`_code_list_healthcare-financing-scheme`),(node:`_code`:`_code_healthcare-financing-scheme` { value:"HF22" }) MERGE (node)-[:usedBy { label:"NPISH financing schemes"}]->(parent);
MERGE (node:`_code`:`_code_healthcare-financing-scheme` { value:"HF23" });
MATCH (parent:`_code_list`:`_code_list_healthcare-financing-scheme`),(node:`_code`:`_code_healthcare-financing-scheme` { value:"HF23" }) MERGE (node)-[:usedBy { label:"Enterprise financing schemes"}]->(parent);
MERGE (node:`_code`:`_code_healthcare-financing-scheme` { value:"HF3" });
MATCH (parent:`_code_list`:`_code_list_healthcare-financing-scheme`),(node:`_code`:`_code_healthcare-financing-scheme` { value:"HF3" }) MERGE (node)-[:usedBy { label:"Out-of-pocket payments"}]->(parent);
