CREATE CONSTRAINT ON (n:`_code_lms-economic-inactivity-reason`) ASSERT n.code IS UNIQUE;
CREATE CONSTRAINT ON (n:`_code_list_lms-economic-inactivity-reason`) ASSERT n.code IS UNIQUE;
CREATE (node:`_code_list`:`_code_list_lms-economic-inactivity-reason` { label:"economicinactivityreason", edition:"one-off" });
MERGE (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"total" });
MATCH (parent:`_code_list`:`_code_list_lms-economic-inactivity-reason`),                (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"total" })                 MERGE (node)-[:usedBy { label:"Total"}]->(parent);
MERGE (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"student" });
MATCH (parent:`_code_list`:`_code_list_lms-economic-inactivity-reason`),                (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"student" })                 MERGE (node)-[:usedBy { label:"Student"}]->(parent);
MERGE (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"looking-after-family-home" });
MATCH (parent:`_code_list`:`_code_list_lms-economic-inactivity-reason`),                (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"looking-after-family-home" })                 MERGE (node)-[:usedBy { label:"Looking after family / home"}]->(parent);
MERGE (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"temp-sick" });
MATCH (parent:`_code_list`:`_code_list_lms-economic-inactivity-reason`),                (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"temp-sick" })                 MERGE (node)-[:usedBy { label:"Temp sick"}]->(parent);
MERGE (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"long-term-sick" });
MATCH (parent:`_code_list`:`_code_list_lms-economic-inactivity-reason`),                (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"long-term-sick" })                 MERGE (node)-[:usedBy { label:"Long-term sick"}]->(parent);
MERGE (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"discouraged" });
MATCH (parent:`_code_list`:`_code_list_lms-economic-inactivity-reason`),                (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"discouraged" })                 MERGE (node)-[:usedBy { label:"Discouraged"}]->(parent);
MERGE (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"retired" });
MATCH (parent:`_code_list`:`_code_list_lms-economic-inactivity-reason`),                (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"retired" })                 MERGE (node)-[:usedBy { label:"Retired"}]->(parent);
MERGE (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"other" });
MATCH (parent:`_code_list`:`_code_list_lms-economic-inactivity-reason`),                (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"other" })                 MERGE (node)-[:usedBy { label:"Other"}]->(parent);
MERGE (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"does-not-want-job" });
MATCH (parent:`_code_list`:`_code_list_lms-economic-inactivity-reason`),                (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"does-not-want-job" })                 MERGE (node)-[:usedBy { label:"Does not want job"}]->(parent);
MERGE (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"wants-a-job" });
MATCH (parent:`_code_list`:`_code_list_lms-economic-inactivity-reason`),                (node:`_code`:`_code_lms-economic-inactivity-reason` { value:"wants-a-job" })                 MERGE (node)-[:usedBy { label:"Wants a job"}]->(parent);
