CREATE CONSTRAINT ON (n:`_code_lms-average-actual-hours-of-work`) ASSERT n.code IS UNIQUE;
CREATE CONSTRAINT ON (n:`_code_list_lms-average-actual-hours-of-work`) ASSERT n.code IS UNIQUE;
CREATE (node:`_code_list`:`_code_list_lms-average-actual-hours-of-work` { label:"averageactualhoursofwork", edition:"one-off" });
MERGE (node:`_code`:`_code_lms-average-actual-hours-of-work` { value:"total-weekly-hours" });
MATCH (parent:`_code_list`:`_code_list_lms-average-actual-hours-of-work`),                (node:`_code`:`_code_lms-average-actual-hours-of-work` { value:"total-weekly-hours" })                 MERGE (node)-[:usedBy { label:"Total weekly hours (millions)"}]->(parent);
MERGE (node:`_code`:`_code_lms-average-actual-hours-of-work` { value:"all-workers" });
MATCH (parent:`_code_list`:`_code_list_lms-average-actual-hours-of-work`),                (node:`_code`:`_code_lms-average-actual-hours-of-work` { value:"all-workers" })                 MERGE (node)-[:usedBy { label:"Average (mean) actual weekly hours of work - All workers"}]->(parent);
MERGE (node:`_code`:`_code_lms-average-actual-hours-of-work` { value:"full-time" });
MATCH (parent:`_code_list`:`_code_list_lms-average-actual-hours-of-work`),                (node:`_code`:`_code_lms-average-actual-hours-of-work` { value:"full-time" })                 MERGE (node)-[:usedBy { label:"Average (mean) actual weekly hours of work - Full-time"}]->(parent);
MERGE (node:`_code`:`_code_lms-average-actual-hours-of-work` { value:"part-time" });
MATCH (parent:`_code_list`:`_code_list_lms-average-actual-hours-of-work`),                (node:`_code`:`_code_lms-average-actual-hours-of-work` { value:"part-time" })                 MERGE (node)-[:usedBy { label:"Average (mean) actual weekly hours of work - Part-time"}]->(parent);
MERGE (node:`_code`:`_code_lms-average-actual-hours-of-work` { value:"workers-with-second-jobs" });
MATCH (parent:`_code_list`:`_code_list_lms-average-actual-hours-of-work`),                (node:`_code`:`_code_lms-average-actual-hours-of-work` { value:"workers-with-second-jobs" })                 MERGE (node)-[:usedBy { label:"Average (mean) actual weekly hours of work - Workers with second jobs"}]->(parent);
