CREATE CONSTRAINT ON (n:`_code_uk-business-broad-industry-group`) ASSERT n.value IS UNIQUE;
CREATE CONSTRAINT ON (n:`_code_list_uk-business-broad-industry-group`) ASSERT n.value IS UNIQUE;
CREATE (node:`_code_list`:`_code_list_uk-business-broad-industry-group` { label:'broadindustrygroup', edition:'one-off' });
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"01-03" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"01-03" }) MERGE (node)-[:usedBy { label:"01-03 : Agriculture, forestry & fishing"}]->(parent);
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"05-39" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"05-39" }) MERGE (node)-[:usedBy { label:"05-39 : Production"}]->(parent);
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"41-43" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"41-43" }) MERGE (node)-[:usedBy { label:"41-43 : Construction"}]->(parent);
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"45" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"45" }) MERGE (node)-[:usedBy { label:"45 : Motor trades"}]->(parent);
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"46" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"46" }) MERGE (node)-[:usedBy { label:"46 : Wholesale"}]->(parent);
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"47" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"47" }) MERGE (node)-[:usedBy { label:"47 : Retail"}]->(parent);
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"49-53" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"49-53" }) MERGE (node)-[:usedBy { label:"49-53 : Transport & Storage (inc. postal)"}]->(parent);
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"55-56" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"55-56" }) MERGE (node)-[:usedBy { label:"55-56 : Accommodation & food services"}]->(parent);
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"58-63" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"58-63" }) MERGE (node)-[:usedBy { label:"58-63 : Information & communication"}]->(parent);
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"64-66" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"64-66" }) MERGE (node)-[:usedBy { label:"64-66 : Finance & insurance"}]->(parent);
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"68" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"68" }) MERGE (node)-[:usedBy { label:"68 : Property"}]->(parent);
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"69-75" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"69-75" }) MERGE (node)-[:usedBy { label:"69-75 : Professional, scientific & technical"}]->(parent);
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"77-82" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"77-82" }) MERGE (node)-[:usedBy { label:"77-82 : Business administration & support services"}]->(parent);
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"84" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"84" }) MERGE (node)-[:usedBy { label:"84 : Public administration & defence"}]->(parent);
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"85" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"85" }) MERGE (node)-[:usedBy { label:"85 : Education"}]->(parent);
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"86-88" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"86-88" }) MERGE (node)-[:usedBy { label:"86-88 : Health"}]->(parent);
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"90-99" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"90-99" }) MERGE (node)-[:usedBy { label:"90-99 : Arts, entertainment, recreation & other"}]->(parent);
MERGE (node:`_code`:`_code_uk-business-broad-industry-group` { value:"total" });
MATCH (parent:`_code_list`:`_code_list_uk-business-broad-industry-group`),(node:`_code`:`_code_uk-business-broad-industry-group` { value:"total" }) MERGE (node)-[:usedBy { label:"Total"}]->(parent);
