CREATE CONSTRAINT ON (n:`_code_wellbeing-measureofwellbeing`) ASSERT n.code IS UNIQUE;
CREATE CONSTRAINT ON (n:`_code_list_wellbeing-measureofwellbeing`) ASSERT n.code IS UNIQUE;
CREATE (node:`_code_list`:`_code_list_wellbeing-measureofwellbeing` { label:"allmeasuresofwellbeing", edition:"one-off" });
MERGE (node:`_code`:`_code_wellbeing-measureofwellbeing` { value:'worthwhile' });
MATCH (parent:`_code_list`:`_code_list_wellbeing-measureofwellbeing`),(node:`_code`:`_code_wellbeing-measureofwellbeing` { value:'worthwhile' }) MERGE (node)-[:usedBy { label:"Worthwhile"}]->(parent);
MERGE (node:`_code`:`_code_wellbeing-measureofwellbeing` { value:'life-satisfaction' });
MATCH (parent:`_code_list`:`_code_list_wellbeing-measureofwellbeing`),(node:`_code`:`_code_wellbeing-measureofwellbeing` { value:'life-satisfaction' }) MERGE (node)-[:usedBy { label:"Life Satisfaction"}]->(parent);
MERGE (node:`_code`:`_code_wellbeing-measureofwellbeing` { value:'anxiety' });
MATCH (parent:`_code_list`:`_code_list_wellbeing-measureofwellbeing`),(node:`_code`:`_code_wellbeing-measureofwellbeing` { value:'anxiety' }) MERGE (node)-[:usedBy { label:"Anxiety"}]->(parent);
MERGE (node:`_code`:`_code_wellbeing-measureofwellbeing` { value:'happiness' });
MATCH (parent:`_code_list`:`_code_list_wellbeing-measureofwellbeing`),(node:`_code`:`_code_wellbeing-measureofwellbeing` { value:'happiness' }) MERGE (node)-[:usedBy { label:"Happiness"}]->(parent);
MERGE (node:`_code`:`_code_wellbeing-measureofwellbeing` { value:"family" });
MATCH (parent:`_code_list`:`_code_list_wellbeing-measureofwellbeing`),                (node:`_code`:`_code_wellbeing-measureofwellbeing` { value:"family" })                 MERGE (node)-[:usedBy { label:"Family"}]->(parent);
MERGE (node:`_code`:`_code_wellbeing-measureofwellbeing` { value:"friends" });
MATCH (parent:`_code_list`:`_code_list_wellbeing-measureofwellbeing`),                (node:`_code`:`_code_wellbeing-measureofwellbeing` { value:"friends" })                 MERGE (node)-[:usedBy { label:"Friends"}]->(parent);
MERGE (node:`_code`:`_code_wellbeing-measureofwellbeing` { value:"happiness-with-health" });
MATCH (parent:`_code_list`:`_code_list_wellbeing-measureofwellbeing`),                (node:`_code`:`_code_wellbeing-measureofwellbeing` { value:"happiness-with-health" })                 MERGE (node)-[:usedBy { label:"Happiness with Health"}]->(parent);
MERGE (node:`_code`:`_code_wellbeing-measureofwellbeing` { value:"time-use" });
MATCH (parent:`_code_list`:`_code_list_wellbeing-measureofwellbeing`),                (node:`_code`:`_code_wellbeing-measureofwellbeing` { value:"time-use" })                 MERGE (node)-[:usedBy { label:"Time Use"}]->(parent);
MERGE (node:`_code`:`_code_wellbeing-measureofwellbeing` { value:"accommodation" });
MATCH (parent:`_code_list`:`_code_list_wellbeing-measureofwellbeing`),                (node:`_code`:`_code_wellbeing-measureofwellbeing` { value:"accommodation" })                 MERGE (node)-[:usedBy { label:"Accommodation"}]->(parent);
MERGE (node:`_code`:`_code_wellbeing-measureofwellbeing` { value:"possessions" });
MATCH (parent:`_code_list`:`_code_list_wellbeing-measureofwellbeing`),                (node:`_code`:`_code_wellbeing-measureofwellbeing` { value:"possessions" })                 MERGE (node)-[:usedBy { label:"Possessions"}]->(parent);
